### ISSUE TITLE
[question]: Multiple inference for single frame

### ISSUE THREAD

**Issue by ManishAwale** [miguelaeh/pipeless#161]
While using `process.json` file, setting the inputs in `inference_input` field for frame data is working for single inference in a frame.
I want to run multiple inferences for each detected objects of a frame as my model doesn't support batch processing. Can this be achieved using `process.json` file? Does `inference_input` supports list of inputs for multiple inferences?

**Comment by miguelaeh** [comment]
Yes, you can simply add multiple stages to your pipeline, each stage will have a `process.json` and will run inference on every frame

**Comment by ManishAwale** [comment]
Does this mean for every object detected from previous stage, i need to add stages dynamically?
what i am trying to do is: first stage detects objects in each frame. In second stage, for every detected objects, i need to run my model individually. For e.g. if 4 objects are detected, i need to run inference 4 times individually and add them as a final frame output.

I can do this in a process.py using a loop. But process.py doesn't allow me to run onnx model in CUDAExecutionProvider. So, I wanted to know if this is possible using process.json

**Comment by miguelaeh** [comment]
Oh, I understand it now. That cannot be achieved with `process.json` right now. You would need to do it using a python file. Why you can't run the model with CUDA execution provider?

**Comment by ManishAwale** [comment]
While running the ONNX model with CUDA execution provider, it is showing segmentation fault and failing during initialization itself

**Comment by ManishAwale** [comment]
The segmentation fault issue when running the ONNX model with CUDAExecutionProvider is now resolved. It was the issue with onnxruntime installation. After copying the working libonnxruntime libraries (.so files) to ~/.pipeless, it is now taking CUDA
